<?xml version="1.0" encoding="utf-8"?><Database Name="EasyUKRainian" Class="VocabularyDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=JASON_STATHAM;Initial Catalog=EasyUKRainian;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="EasyUKRainianConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Topic" Member="Topic">
    <Type Name="Topic">
      <Column Name="TopicID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Header" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Capacity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MinScoreForAccess" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Topic_Word" Member="Word" ThisKey="TopicID" OtherKey="TopicID" Type="Word" />
    </Type>
  </Table>
  <Table Name="dbo.Word" Member="Word">
    <Type Name="Word">
      <Column Name="WID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TopicID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Word" Member="Word1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Word_Translate" Member="Translate" ThisKey="WID" OtherKey="TID" Type="Translate" />
      <Association Name="Topic_Word" Member="Topic" ThisKey="TopicID" OtherKey="TopicID" Type="Topic" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Translate" Member="Translate">
    <Type Name="Translate">
      <Column Name="TID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Translate" Member="Translate1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ImageLink" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Word_Translate" Member="Word" ThisKey="TID" OtherKey="WID" Type="Word" IsForeignKey="true" />
    </Type>
  </Table>
</Database>