//------------------------------------------------------------------------------
<<<<<<< HEAD
// <автоматически создаваемое>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода. 
// </автоматически создаваемое>
=======
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
>>>>>>> origin/Andrew
//------------------------------------------------------------------------------

namespace EasyUKRaine.kuchmynda {
    
    
    public partial class Tags {
        
        /// <summary>
<<<<<<< HEAD
        /// Tages элемент управления.
        /// </summary>
        /// <remarks>
        /// Автоматически создаваемое поле.
        /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
=======
        /// Tages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
>>>>>>> origin/Andrew
        /// </remarks>
        protected global::System.Web.UI.WebControls.Table Tages;
    }
}
